{
 "title": "Quarkus CO2 per API Call Dashboard",
 "time": { "from": "now-5m", "to": "now" },
 "panels": [
  {
   "title": "CO2 Emissions per Service getData (HTTP GET) Operation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 0 },
   "targets": [
    {
     "expression": "((($CPUDemandMSPerOperation/1000)*($CPUCO2EmissionsPerCoreMinute/60))+(($MemoryDemandkBytePerOperation/1000/1000)*($MemoryCO2EmissionsPerGBMinute/60)))/$CallCountPerOperation",
     "type": "math"
    }
   ]
  },
  {
   "title": "CO2 Emissions per Service postData (HTTP POST) Operation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 10, "y": 0 },
   "targets": [
    {
     "expression": "((($CPUDemandMSPerOperation/1000)*($CPUCO2EmissionsPerCoreMinute/60))+(($MemoryDemandkBytePerOperation/1000/1000)*($MemoryCO2EmissionsPerGBMinute/60)))/$CallCountPerOperation",
     "type": "math"
    }
   ]
  },
  {
   "title": "CO2 Emissions per Service deleteData (HTTP DELETE) Operation",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 10, "x": 0, "y": 7 },
   "targets": [
    {
     "expression": "((($CPUDemandMSPerOperation/1000)*($CPUCO2EmissionsPerCoreMinute/60))+(($MemoryDemandkBytePerOperation/1000/1000)*($MemoryCO2EmissionsPerGBMinute/60)))/$CallCountPerOperation",
     "type": "math"
    }
   ]
  }
 ]
}